/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package strava.effort.parser

class App {
    private val startDate = "2015-06-29"
    private val aggregator: Aggregator = Aggregator()
    fun run() {
        aggregator.aggregate(startDate)
    }
}

fun main() {
    App().run()
}
